#define INPUT_ACTION_MESSAGE "Input your choice [1..4]: "
#define INPUT_YOGURT_MESSAGE "Input your yogurt [chocolate/vanilla/strawberry]: "
#define INPUT_YOGURT_TOPPING_MESSAGE "Input your topping [kitkat/jelly/kiwi/mango]: "
#define INPUT_YOGURT_TOPPING_SIZE_MESSAGE "Input your size [100...500]: "
#define INPUT_PURCHASE_CONFIRMATION "Are you sure [y/n]: "

#define DETAIL_PURCHASE_MESSAGE "Detail Purchase: "
#define YOGURT_NAME_MESSAGE "Name"
#define YOGURT_TOPPING_NAME_MESSAGE "Topping"
#define YOGURT_TOPPING_SIZE_MESSAGE "Size"
#define YOGURT_PRICE_MESSAGE "Price"
#define DATA_ADDED_MESSAGE "Data succesfully added . . ."